const state = {
  disciplineControlForms: [
    {
      name: 'Экзамен',
      tooltip: 'Экзаменом называется проверка знаний студента по одному из изученных ранее предметов. По итогам сдачи обязательно выставляется оценка, обычно в балльной системе. Если с первого раза сдать не удалось, студент имеет право на пересдачу.'
    },
    {
      name: 'Дифференцированный зачёт',
      tooltip: 'Семестровый дифференцированный зачет - это форма итогового контроля, которая предусматривает оценивание усвоения студентами обучающего материала по определенной учебной дисциплине в основном на основании результатов выполненных ими индивидуальных заданий.'
    },
    {
      name: 'Зачёт',
      tooltip: 'Вместо применяемого при экзамене выставления отметки, при успешном прохождении зачёта в ведомость и зачётную книжку ставится лишь пометка об успешном прохождении испытания по учебной дисциплине или её разделу (сама такая пометка тоже называется «зачётом»). Для получения зачёта необходимо набрать <strong>50 баллов</strong>'
    }
  ],
  disciplines: [
    {
      title: 'Наименование Дисциплины №1',
      points: 0,
      controlEvents: [
        {
          week: 9,
          title: 'Домашнее задание (ДЗ.1)',
          pointsMax: 20,
          points: 20,
          additional: false,
        },
        {
          week: 10,
          title: 'Активность/Посещаемость (А/П.1)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 14,
          title: 'Домашнее задание (ДЗ.2)',
          pointsMax: 20,
          points: 20,
          additional: false,
        },
        {
          week: 15,
          title: 'Активность/Посещаемость (А/П.2)',
          pointsMax: 5,
          points: 4.4,
          additional: false,
        },
        {
          week: 15,
          title: 'Домашнее задание (ДЗ.3)',
          pointsMax: 20,
          points: 20,
          additional: false,
        },
        {
          week: 16,
          title: 'Активность/Посещаемость (А/П.3)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 16,
          title: 'Зачёт (З.1)',
          pointsMax: 25,
          points: 16.6,
          additional: true,
        },
        {
          week: 18,
          title: 'Дифференцированный зачёт',
          pointsMax: 25,
          points: 9,
          additional: false,
        },
      ],
      controlForm: 'Дифференцированный зачёт',
      department: 'Институт ...',
      teacher: ['Преподаватель № 1', 'Преподаватель № 2'],
      consultations: 'Преподаватель № 1, Каждый числитель, Понедельник, электронная почта, 12:20',
      resourcesLink: '#',
      news: [],
    },
    {
      title: 'Наименование Дисциплины №2',
      points: 0,
      controlEvents: [
        {
          week: 4,
          title: 'Семинар (С.1)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 4,
          title: 'Рубежный контроль (РК.1)',
          pointsMax: 5,
          points: 4,
          additional: false,
        },
        {
          week: 6,
          title: 'Семинар (С.2)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 8,
          title: 'Семинар (С.3)',
          pointsMax: 5,
          points: 4,
          additional: false,
        },
        {
          week: 10,
          title: 'Практическое занятие (ПЗ.1)',
          pointsMax: 6,
          points: 5,
          additional: false,
        },
        {
          week: 10,
          title: 'Домашнее задание (ДЗ.1)',
          pointsMax: 6,
          points: 3,
          additional: false,
        },
        {
          week: 11,
          title: 'Практическое занятие (ПЗ.2)',
          pointsMax: 6,
          points: 5,
          additional: false,
        },
        {
          week: 12,
          title: 'Рубежный контроль (РК.2)',
          pointsMax: 5,
          points: 4,
          additional: false,
        },
        {
          week: 14,
          title: 'Практическое занятие (ПЗ.3)',
          pointsMax: 6,
          points: 5,
          additional: false,
        },
        {
          week: 14,
          title: 'Рубежный контроль (РК.3)',
          pointsMax: 5,
          points: 4,
          additional: false,
        },
        {
          week: 16,
          title: 'Практическое занятие (ПЗ.4)',
          pointsMax: 6,
          points: 5,
          additional: false,
        },
        {
          week: 16,
          title: 'Домашнее задание (ДЗ.2)',
          pointsMax: 6,
          points: 3,
          additional: false,
        },
        {
          week: 16,
          title: 'Рубежный контроль (РК.4)',
          pointsMax: 4,
          points: 4,
          additional: false,
        },
        {
          week: 18,
          title: 'Экзамен',
          pointsMax: 30,
          points: 30,
          additional: false,
        },
      ],
      controlForm: 'Экзамен',
      department: 'Кафедра ...',
      teacher: ['Преподаватель № 1', 'Преподаватель № 2'],
      consultations: 'Преподаватель № 1, Каждую неделю, Понедельник, 3334, Ссылка, 10:00',
      resourcesLink: '#',
      news: []
    },
    {
      title: 'Наименование Дисциплины №3',
      points: 0,
      controlEvents: [
        {
          week: 8,
          title: 'Практическое занятие (ПЗ.1)',
          pointsMax: 22,
          points: 22,
          additional: false,
        },
        {
          week: 8,
          title: 'Лекция (Л.1)',
          pointsMax: 15,
          points: 15,
          additional: false,
        },
        {
          week: 8,
          title: 'Контрольное мероприятие (КМ.1)',
          pointsMax: 7,
          points: 7,
          additional: false,
        },
        {
          week: 11,
          title: 'Рубежный контроль (РК.1)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 16,
          title: 'Практическое занятие (ПЗ.2)',
          pointsMax: 22,
          points: 22,
          additional: false,
        },
        {
          week: 16,
          title: 'Лекция (Л.2)',
          pointsMax: 15,
          points: 15,
          additional: false,
        },
        {
          week: 16,
          title: 'Рубежный контроль (РК.2)',
          pointsMax: 14,
          points: 13.16,
          additional: false,
        }
      ],
      controlForm: 'Дифференцированный зачёт',
      department: 'Кафедра ...',
      teacher: ['Преподаватель № 1','Преподаватель № 2'],
      consultations: 'Преподаватель № 2, Каждый числитель, Вторник, 3341, 14:30',
      resourcesLink: '',
      news: []
    },
    {
      title: 'Наименование Дисциплины №4',
      points: 0,
      controlEvents: [
        {
          week: 6,
          title: 'Лабораторная работа (ЛР.1)',
          pointsMax: 8,
          points: 8,
          additional: false,
        },
        {
          week: 8,
          title: 'Посещаемость (П.1)',
          pointsMax: 10,
          points: 10,
          additional: false,
        },
        {
          week: 12,
          title: 'Лабораторная работа (ЛР.2)',
          pointsMax: 8,
          points: 8,
          additional: false,
        },
        {
          week: 13,
          title: 'Тест (Т.1)',
          pointsMax: 1,
          points: 1,
          additional: false,
        },
        {
          week: 14,
          title: 'Лабораторная работа (ЛР.3)',
          pointsMax: 8,
          points: 8,
          additional: false,
        },
        {
          week: 14,
          title: 'Лабораторная работа (ЛР.4)',
          pointsMax: 8,
          points: 8,
          additional: false,
        },
        {
          week: 16,
          title: 'Лабораторная работа (ЛР.5)',
          pointsMax: 8,
          points: 8,
          additional: false,
        },
        {
          week: 16,
          title: 'Лабораторная работа (ЛР.6)',
          pointsMax: 8,
          points: 8,
          additional: false,
        },
        {
          week: 17,
          title: 'Активность (А.1)',
          pointsMax: 9,
          points: 9,
          additional: false,
        },
        {
          week: 17,
          title: 'Индивидуальное задание (ИЗ.1)',
          pointsMax: 8,
          points: 8,
          additional: true,
        },
        {
          week: 17,
          title: 'Итоговая контрольная работа (ИКР.1)',
          pointsMax: 32,
          points: 32,
          additional: false,
        },
        {
          week: 17,
          title: 'Индивидуальное задание (ИЗ.2)',
          pointsMax: 8,
          points: 8,
          additional: true,
        },
      ],
      controlForm: 'Дифференцированный зачёт',
      department: 'Институт ...',
      teacher: ['Преподаватель № 1'],
      consultations: 'Каждую неделю, Понедельник, Ссылка, 16:10',
      resourcesLink: '',
      news: []
    },
    {
      title: 'Наименование Дисциплины №5',
      points: 0,
      controlEvents: [
        {
          week: 2,
          title: 'Лабораторная работа (ЛР.1)',
          pointsMax: 6,
          points: 6,
          additional: false,
        },
        {
          week: 4,
          title: 'Лабораторная работа (ЛР.2)',
          pointsMax: 10,
          points: 10,
          additional: false,
        },
        {
          week: 6,
          title: 'Лабораторная работа (ЛР.3)',
          pointsMax: 10,
          points: 10,
          additional: false,
        },
        {
          week: 8,
          title: 'Лабораторная работа (ЛР.4)',
          pointsMax: 10,
          points: 10,
          additional: false,
        },
        {
          week: 10,
          title: 'Лабораторная работа (ЛР.5)',
          pointsMax: 10,
          points: 10,
          additional: false,
        },
        {
          week: 12,
          title: 'Лабораторная работа (ЛР.6)',
          pointsMax: 10,
          points: 10,
          additional: false,
        },
        {
          week: 14,
          title: 'Лабораторная работа (ЛР.7)',
          pointsMax: 10,
          points: 10,
          additional: false,
        },
        {
          week: 16,
          title: 'Лабораторная работа (ЛР.8)',
          pointsMax: 10,
          points: 10,
          additional: false,
        },
        {
          week: 17,
          title: 'Активность/Посещаемость (А/П.1)',
          pointsMax: 24,
          points: 24,
          additional: false,
        },
      ],
      controlForm: 'Зачёт',
      department: 'Кафедра ...',
      teacher: ['Преподаватель № 1'],
      consultations: '',
      resourcesLink: '',
      news: []
    },
    {
      title: 'Наименование Дисциплины №6',
      points: 0,
      controlEvents: [
        {
          week: 6,
          title: 'Тест (Т.1)',
          pointsMax: 6,
          points: 5,
          additional: false,
        },
        {
          week: 10,
          title: 'Самостоятельная работа (СР.1)',
          pointsMax: 10,
          points: 7,
          additional: false,
        },
        {
          week: 15,
          title: 'Итоговая контрольная работа (ИКР.1)',
          pointsMax: 14,
          points: 11,
          additional: false,
        },
        {
          week: 17,
          title: 'Активность/Посещаемость (А/П.1)',
          pointsMax: 30,
          points: 27,
          additional: false,
        },
        {
          week: 18,
          title: 'Дифференцированный зачёт',
          pointsMax: 40,
          points: 37,
          additional: false,
        },
      ],
      controlForm: 'Дифференцированный зачёт',
      department: 'Кафедра ...',
      teacher: ['Преподаватель № 1'],
      consultations: '',
      resourcesLink: '',
      news: []
    },
    {
      title: 'Наименование Дисциплины №7',
      points: 0,
      controlEvents: [
        {
          week: 8,
          title: 'Контрольное мероприятие (КМ.1)',
          pointsMax: 32,
          points: 16,
          additional: false,
        },
        {
          week: 12,
          title: 'Контрольное мероприятие (КМ.2)',
          pointsMax: 16,
          points: 8,
          additional: false,
        },
        {
          week: 17,
          title: 'Контрольное мероприятие (КМ.3)',
          pointsMax: 52,
          points: 35,
          additional: false,
        },
      ],
      controlForm: 'Зачёт',
      department: '',
      teacher: ['Преподаватель № 1', 'Преподаватель № 2'],
      consultations: 'Преподаватель № 2, Каждую неделю, Понедельник, 5101, 15:30',
      resourcesLink: '',
      news: []
    },
    {
      title: 'Наименование Дисциплины №8',
      points: 0,
      controlEvents: [
        {
          week: 1,
          title: 'Практическое занятие (ПЗ.1)',
          pointsMax: 10,
          points: 10,
          additional: false,
        },
        {
          week: 3,
          title: 'Практическое занятие (ПЗ.2)',
          pointsMax: 10,
          points: 10,
          additional: false,
        },
        {
          week: 9,
          title: 'Практическое занятие (ПЗ.3)',
          pointsMax: 10,
          points: 10,
          additional: false,
        },
        {
          week: 15,
          title: 'Практическое занятие (ПЗ.4)',
          pointsMax: 10,
          points: 5,
          additional: false,
        },
        {
          week: 15,
          title: 'Рубежный контроль (РК.1)',
          pointsMax: 20,
          points: 18.6,
          additional: false,
        },
        {
          week: 16,
          title: 'Активность/Посещаемость (А/П.1)',
          pointsMax: 10,
          points: 5,
          additional: false,
        },
        {
          week: 16,
          title: 'Практическое занятие (ПЗ.5)',
          pointsMax: 10,
          points: 5,
          additional: false,
        },
        {
          week: 16,
          title: 'Индивидуальное задание (ИЗ.1)',
          pointsMax: 20,
          points: 20,
          additional: false,
        },
      ],
      controlForm: 'Зачёт',
      department: 'Кафедра ...',
      teacher: ['Преподаватель № 1'],
      consultations: 'Каждую неделю, Вторник, 3341, 17:30',
      resourcesLink: '',
      news: []
    },
    {
      title: 'Наименование Дисциплины №9',
      points: 0,
      controlEvents: [
        {
          week: 2,
          title: 'Лабораторная работа (ЛР.1)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 4,
          title: 'Лабораторная работа (ЛР.2)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 6,
          title: 'Лабораторная работа (ЛР.3)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 8,
          title: 'Лабораторная работа (ЛР.4)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 10,
          title: 'Лабораторная работа (ЛР.5)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 12,
          title: 'Лабораторная работа (ЛР.6)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 14,
          title: 'Лабораторная работа (ЛР.7)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 16,
          title: 'Активность/Посещаемость (А/П.1)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 18,
          title: 'Итоговая контрольная работа (ИКР.1)',
          pointsMax: 60,
          points: 60,
          additional: false,
        },
      ],
      controlForm: 'Дифференцированный зачёт',
      department: 'Институт ...',
      teacher: ['Преподаватель № 1', 'Преподаватель № 2', 'Преподаватель № 3'],
      consultations: 'Преподаватель № 1, Каждую неделю, Понедельник, 4100а, каждый день, 10:00',
      resourcesLink: '',
      news: []
    },
    {
      title: 'Наименование Дисциплины №10',
      points: 0,
      controlEvents: [
        {
          week: 2,
          title: 'Лабораторная работа (ЛР.1)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 4,
          title: 'Лабораторная работа (ЛР.2)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 6,
          title: 'Лабораторная работа (ЛР.3)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 8,
          title: 'Лабораторная работа (ЛР.4)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 10,
          title: 'Лабораторная работа (ЛР.5)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 10,
          title: 'Тест (Т.1)',
          pointsMax: 10,
          points: 8.6,
          additional: false,
        },
        {
          week: 12,
          title: 'Лабораторная работа (ЛР.6)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 14,
          title: 'Лабораторная работа (ЛР.7)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 16,
          title: 'Лабораторная работа (ЛР.8)',
          pointsMax: 5,
          points: 5,
          additional: false,
        },
        {
          week: 17,
          title: 'Тест (Т.2)',
          pointsMax: 25,
          points: 25,
          additional: false,
        },
        {
          week: 17,
          title: 'Тест (Т.3)',
          pointsMax: 25,
          points: 22,
          additional: false,
        },
        {
          week: 18,
          title: 'Дифференцированный зачёт',
          pointsMax: 0,
          points: 0,
          additional: false,
        },
      ],
      controlForm: 'Дифференцированный зачёт',
      department: 'Институт ...',
      teacher: ['Преподаватель № 1'],
      consultations: 'Каждую неделю, Понедельник, 4313, 12:00',
      resourcesLink: '',
      news: []
    },
  ],
};
const mutations = {

};
const actions = {

}
const getters = {
  //При получении геттера каждый раз идёт пересчёт итоговой суммы баллов
  getDisciplines(state) {
    state.disciplines.forEach(item => {
      item.points = +item.controlEvents.reduce((sum, current) => {
        return sum + current.points;
      }, 0).toFixed(2);
    })
    return state.disciplines;
  },
  getDisciplineListOnly(state) {
    let array = [];
    state.disciplines.forEach(item => array.push(item.title));
    return array;
  },
  getDisciplineControlForms(state) {
    return state.disciplineControlForms;
  }
}
export default {state, mutations, getters, actions}
